# Generated by Django 3.2.16 on 2022-12-15 14:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.date(2022, 12, 15))),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.date(2022, 12, 15))),
                ('deleted_at', models.DateTimeField(blank=True, default=datetime.date(2022, 12, 15))),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('last_scanned', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.date(2022, 12, 15))),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.date(2022, 12, 15))),
                ('deleted_at', models.DateTimeField(blank=True, default=datetime.date(2022, 12, 15))),
            ],
        ),
        migrations.AddField(
            model_name='website',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.date(2022, 12, 15)),
        ),
        migrations.AddField(
            model_name='website',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=datetime.date(2022, 12, 15)),
        ),
        migrations.AddField(
            model_name='website',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.date(2022, 12, 15)),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(null=True)),
                ('status', models.CharField(max_length=50)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.block')),
            ],
        ),
        migrations.CreateModel(
            name='PageSpeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.date(2022, 12, 15))),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.date(2022, 12, 15))),
                ('deleted_at', models.DateTimeField(blank=True, default=datetime.date(2022, 12, 15))),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.page')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.website'),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.block')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(null=True)),
                ('status', models.CharField(max_length=50)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.block')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.page'),
        ),
    ]
