# Generated by Django 3.2.16 on 2022-12-15 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20221215_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='block',
            name='deleted_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='updated_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='page',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='page',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pagespeed',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pagespeed',
            name='deleted_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='pagespeed',
            name='updated_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='website',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='website',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
