# Generated by Django 3.2.16 on 2022-12-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20221215_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
