# Generated by Django 3.2.16 on 2022-12-16 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_page_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='website',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='website.website'),
        ),
    ]
