# Generated by Django 3.2.16 on 2022-12-19 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_content_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='block',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='website.block'),
        ),
    ]
