# Generated by Django 3.2.16 on 2022-12-19 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_content_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
