# Generated by Django 3.2.16 on 2022-12-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_content_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('UNCHANGED', 'Unchanged'), ('EDITED', 'Edited'), ('DELETED', 'Deleted')], max_length=50),
        ),
    ]
