# Generated by Django 3.2.16 on 2022-12-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_content_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[(1, []), (2, []), (3, [])], max_length=50),
        ),
    ]
