# Generated by Django 3.2.16 on 2022-12-20 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_content_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='status',
        ),
        migrations.AlterField(
            model_name='result',
            name='block',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='block', to='website.block'),
        ),
        migrations.AlterField(
            model_name='result',
            name='status',
            field=models.CharField(choices=[(1, []), (2, []), (3, [])], max_length=50),
        ),
    ]
