# Generated by Django 3.2.16 on 2023-02-01 08:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('status', models.CharField(choices=[('NOT_STARTED', []), ('SITEMAP', []), ('ROBOTS', []), ('METATAGS', []), ('GOOGLE', []), ('NICEURL', []), ('COMPLETED', [])], default=1, max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('last_scanned', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(choices=[('NOT_STARTED', []), ('SITEMAP', []), ('ROBOTS', []), ('METATAGS', []), ('GOOGLE', []), ('NICEURL', [])], default=1, max_length=50)),
                ('status', models.CharField(choices=[('NOT_STARTED', []), ('SUCCESS', []), ('FAILED', [])], default=1, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('check_list', models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='api.checklist')),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('website', models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan', to='api.website')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.UUIDField(editable=False)),
                ('data', models.JSONField()),
                ('status', models.CharField(choices=[(1, []), (2, []), (3, [])], max_length=50)),
                ('checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('block', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.block')),
            ],
        ),
        migrations.CreateModel(
            name='PageSpeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.page')),
            ],
        ),
        migrations.CreateModel(
            name='PageResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule', models.CharField(choices=[(1, []), (2, []), (3, [])], max_length=50)),
                ('status', models.CharField(choices=[(1, []), (2, []), (3, [])], max_length=50)),
                ('value', models.JSONField()),
                ('attribute', models.CharField(max_length=255, null=True)),
                ('group_id', models.UUIDField(editable=False)),
                ('page', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='page_results', to='api.page')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='website',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='api.website'),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.block')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('block', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='api.block')),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='website',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='api.website'),
        ),
        migrations.AddField(
            model_name='block',
            name='page',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='api.page'),
        ),
    ]
