# Generated by Django 3.2.16 on 2023-01-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[(1, []), (1, []), (2, [])], default=1, max_length=50),
        ),
    ]
