# Generated by Django 3.2.16 on 2023-02-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageresult',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='pageresult',
            name='status',
        ),
    ]
