# Generated by Django 3.2.16 on 2023-02-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230201_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageresult',
            name='className',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
