# Generated by Django 3.2.16 on 2023-01-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230127_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(1, []), (1, []), (2, [])], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[(1, []), (2, []), (3, [])], default=1, max_length=50),
        ),
    ]
