# Generated by Django 3.2.16 on 2023-02-01 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pageresult_classname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageresult',
            name='group_id',
        ),
    ]
