# Generated by Django 3.2.16 on 2023-01-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230127_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', []), ('SITEMAP', []), ('ROBOTS', [])], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', []), ('SUCCESS', []), ('FAILED', [])], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('NOT_STARTED', []), ('SITEMAP', []), ('ROBOTS', [])], default=1, max_length=50),
        ),
    ]
