# Generated by Django 3.2.16 on 2023-01-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230127_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', []), ('SITEMAP', []), ('ROBOTS', []), ('METATAGS', []), ('GOOGLE', []), ('NICEURL', [])], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('NOT_STARTED', []), ('SITEMAP', []), ('ROBOTS', []), ('METATAGS', []), ('GOOGLE', []), ('NICEURL', [])], default=1, max_length=50),
        ),
    ]
