# Generated by Django 3.2.16 on 2023-01-06 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_block_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='page',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='api.page'),
        ),
    ]
