# Generated by Django 3.2.17 on 2023-02-08 08:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_pageresult_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageresult',
            name='value',
        ),
        migrations.CreateModel(
            name='PageValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('page_result', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='page_values', to='api.pageresult')),
            ],
        ),
    ]
