# Generated by Django 3.2.17 on 2023-02-08 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230208_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagevalue',
            name='page_result',
        ),
        migrations.AddField(
            model_name='pageresult',
            name='page_value',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='page_result', to='api.pagevalue'),
        ),
    ]
