# Generated by Django 3.2.17 on 2023-02-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230208_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('SITEMAP', []), ('GET_DATA', []), ('COMPARE_BLOCKS', []), ('CHECK_DELETED', []), ('COMPLETED', [])], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
