# Generated by Django 3.2.17 on 2023-02-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_scan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[(1, []), (2, []), (3, []), (4, [])], max_length=50),
        ),
    ]
