# Generated by Django 3.2.17 on 2023-03-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_scan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagespeed',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='pagespeed',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='pagespeed',
            name='type',
            field=models.CharField(choices=[(1, []), (2, [])], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagespeed',
            name='v_users',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pagespeed',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True),
        ),
    ]
