# Generated by Django 3.2.17 on 2023-03-06 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20230306_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagespeed',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_speed', to='api.page'),
        ),
    ]
